extra-deps: 
- shelly-1.8.0
ghc-options: {'$everything': -threaded}
local-bin-path:
  ./executables
packages:
- location: ./luna-manager
- extra-dep: true
  location: {commit: fb2c116d6dd17cf4564aad4c1985f685e5965af2, git: 'https://github.com/luna/luna.git'}
  subdirs:
    - lib/container
    - lib/prologue
    - lib/typelevel
    - lib/convert
    - lib/layered-state
    - lib/functor-utils
    - lib/impossible
    - lib/lens-utils
    - lib/monoid
    - lib/monad-branch
    - lib/th-builder
resolver: lts-12.26