extra-deps: 
- container-1.1.6
- prologue-3.2.6
- typelevel-1.2.3
- convert-1.5.1
# - dependent-state-1.1
- functor-utils-1.17.2
- impossible-1.1.4
- lens-utils-1.4.6
- monoid-0.1.9
- shelly-1.8.0
- monad-branch-1.0.4
ghc-options: {'$everything': -threaded}
local-bin-path:
  ./executables
packages:
- location: ./luna-manager
- extra-dep: true
  location: {commit: f1be47f0dbc6029d2ffcc6f0eb92fc9eb78bc3b6, git: 'https://github.com/luna/dependent-state.git'}
resolver: lts-12.26